spring:
  application:
    name: item-service
  clound:
    config:
      override-none: true
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka, http://127.0.0.1:2002/eureka
